name: angulardartuibootstrap
description: A sample web application
dependencies:
  angular: any
  angular_dart_ui_bootstrap: any
  browser: any
transformers:
- $dart2js:
    checked: false
    suppressWarnings: true
    suppressHints: true
    terse: true
